### ISSUE TITLE
Typo in professional experience

### ISSUE THREAD

**Issue by alejgh** [thewilly/resume#1]
Hello. I have seen a typo in the Spanish translation of the professional experience section. 
<img width="944" alt="prof_exp" src="https://user-images.githubusercontent.com/29005950/84148310-1c33e700-aa5f-11ea-930e-8c15376014d4.png">

I think the title should be "EXPERIENCIA PROFESIONAL" and not "EXPRERIENCIA PROFESIONAL". 

Thank you.

**Comment by thewilly** [comment]
🤦🏻‍♂️🤣🤣 love u

Guillermo Facundo Colunga,
Researcher at WESO, University of Oviedo.
C/ Calvo Sotelo 18,
3ª Planta, laboratorio 209,
Asturias - 33007.
T: 98510-3397
